version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/requirements.txt
    - pip:
        - git+https://github.com/gjheij/lazyfmri.git
        - git+https://github.com/VU-Cog-Sci/prfpy.git
        - pip list
        - python --version
        - ls -l doc/
        - ls -l doc/source/
        - ls -l doc/requirements.txt
        - cat doc/requirements.txt

sphinx:
  configuration: doc/source/conf.py
